name: Promote

permissions:
  contents: write # For creating releases
  id-token: write # For JFrog OIDC authentication

on:
  workflow_call:
    inputs:
      build-number:
        type: string
        description: Build number used to build artifact to be promoted
      target-repository:
        type: string
        description: Repository to promote to
      target-branch:
        type: string
        description: Target branch to promote token
      jf-target-build:
        type: string
        description: Target build name
        default: spring-data-aerospike-starters
      source-branch:
        type: string
        required: true
        description: Source branch to merge from
    secrets:
      AEROSPIKE_SA_CICD_USERNAME:
        required: true
      AEROSPIKE_SA_CICD_PASSWORD:
        required: true
      CLIENT_BOT_PAT:
        required: true
      JFROG_OIDC_PROVIDER:
        required: true
      JFROG_OIDC_AUDIENCE:
        required: true

jobs:
  promote:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    outputs:
      build-name-number: ${{ steps.get-build-name-number.outputs.build-name-numbers }}
      artifact-version: ${{ steps.get-artifact-version.outputs.artifact-version }}
      release-notes: ${{ steps.get-release-notes.outputs.release-notes }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Debug step
        run: |
          echo "build-number: ${{ inputs.build-number }}"
          echo "target-repository: ${{ inputs.target-repository }}"
          echo "target-branch: ${{ inputs.target-branch }}"
          echo "jf-target-build: ${{ inputs.jf-target-build }}"
          echo "source-branch: ${{ inputs.source-branch }}"

      # Setting up jfrog cli
      - name: Setup jfrog shell
        uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
        env:
          JF_URL: ${{ vars.JFROG_PLATFORM_URL }}
          JF_PROJECT: database
        with:
          oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
          oidc-audience: ${{ vars.OIDC_AUDIENCE }}

      # Needed since we are using actions which are part of the repository
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Fetch the whole history to prevent unrelated history errors
          fetch-depth: "0"
          ref: ${{ inputs.target-branch }}
          token: ${{ secrets.CLIENT_BOT_PAT }}

      # Getting build info which will allow us to get information about the build we are promoting
      - name: Get info
        id: get-build-info
        run: |
          API_PATH="/api/build/${{ inputs.jf-target-build }}/${{ inputs.build-number }}?project=database"
          status_code=$(jf rt curl "${API_PATH}" -o /dev/null -s -w "%{http_code}")

          # Exit with 1 unless the request succeeded (HTTP 200)
          if [[ "$status_code" -ne 200 ]]; then
            echo "ERROR: could not fetch build for build number ${{ inputs.build-number }} (HTTP $status_code)" >&2

            exit 1
          fi
          
          echo build-info=$(jf rt curl "${API_PATH}" ) >> $GITHUB_OUTPUT

      # Snapshot builds are not promoted to production
      - name: Check if snapshot build
        id: check-snapshot
        run: |
          BUILD_INFO='${{ steps.get-build-info.outputs.build-info }}'
          BUILD_ID=$(echo "$BUILD_INFO" | jq -r '.buildInfo.modules[] | select(.id | test("buildinfo")) | .id')
          # extracting snapshot from build-nfo name. Not ideal, but we don't have is_snapshot information in JF yet          
          # Extract version from build ID
          # Format: <artifact>/<number>-buildinfo-<version>_hash
          if [[ "$BUILD_ID" =~ buildinfo-([0-9.]+(-SNAPSHOT)?) ]]; then
            VERSION="${BASH_REMATCH[1]}"
          echo "Parsed version: $VERSION"
            else
            echo "ERROR: Could not parse version"
          fi
          
          echo "Parsed version: $VERSION"
          
          if [[ "$VERSION" == *"-SNAPSHOT" ]]; then
            echo "Error: Build ${{ inputs.jf-target-build }} with build number ${{ inputs.build-number }} is a SNAPSHOT build. Snapshots are not promoted to production."
            # exit 1
          fi

      # Fetching commit hash from the build info. The commit hash is used for SNAPSHOT builds
      - name: Get commit hash from repo
        id: get-commit-hash
        run: |
          BUILD_INFO='${{ steps.get-build-info.outputs.build-info }}'

          # Try to get from vcs first
          COMMIT_HASH=$(echo "$BUILD_INFO" | jq -r '.buildInfo.vcs[0].revision // empty')

          if [ -z "$COMMIT_HASH" ] || [ "$COMMIT_HASH" == "null" ]; then
            # Fallback: extract from module ID
            COMMIT_HASH=$(echo "$BUILD_INFO" | jq -r '.buildInfo.modules[0].id' | sed -E 's/.*SNAPSHOT_(.*)$/\1/')
          fi
          echo "commit-hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

      # Fetching build name for build promotion process. The build name will contain build numbers.
      # This command parses json and pulls out the build name
      - name: Get build name
        id: get-build-name
        run: |
          echo build-names=$(echo '${{ steps.get-build-info.outputs.build-info }}' | jq -r '.buildInfo.name') >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          echo "commit-hash: '${{ steps.get-commit-hash.outputs.commit-hash }}'"
          echo "build-name: '${{ steps.get-build-name.outputs.build-names }}'"

      # Promoting build to production
      - name: Promote build
        shell: bash
        run: |
          BUILD_NAME="${{ steps.get-build-name.outputs.build-names }}"
          BUILD_NUMBER="${{ inputs.build-number }}"
    
          if [ -z "$BUILD_NAME" ]; then
            echo "Error: Missing build name"
            exit 1
          fi
    
          echo "Promoting build '$BUILD_NAME' (build #$BUILD_NUMBER) to ${{ inputs.target-repository }}"
          jf rt build-promote --copy=true "$BUILD_NAME" "$BUILD_NUMBER" "${{ inputs.target-repository }}"

      # Fetching release notes from commit logs
      - name: Generate release notes
        id: get-release-notes
        run: |
          RELEASE_NOTES=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s")
          echo "release-notes<<EOF" >> $GITHUB_OUTPUT
          echo "${RELEASE_NOTES}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Debug print release notes
        run: |
          echo "Changes for release ${{ steps.get-artifact-version.outputs.artifact-version }}"
          echo "${{ steps.get-release-notes.outputs.release-notes }}"
      
      # Fast forward the target branch to the source branch.
#      - name: Fast forward
#        shell: bash
#        run: |
#          # Making sure we have latest history in place to be able to fast forward merge
#          git status
#          git checkout ${{ inputs.source-branch }}
#          git checkout ${{ inputs.target-branch }}
#          git merge --ff-only ${{ inputs.source-branch }}
#
#      # Adding commit message for promotion
#      - name: Add tagging message
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "Promote to prod [skip ci]"
#          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
#          tagging_message: Promote to PROD
#          branch: ${{ inputs.target-branch }}

      # Pushing changes to remote head branch
      # This needs updating to create PR instead of direct push
#      - name: Upload changes to remote head branch
#        shell: bash
#        run: git push

      # Passing build-name-numbers and artifact-version to the next job
      - name: Get build name with build number
        id: get-build-name-number
        run: |
          echo "DEBUG: inputs.build-number='${{ inputs.build-number }}'"
          BUILD_NAME=$(echo '${{ steps.get-build-info.outputs.build-info }}' | jq -r '.buildInfo.name')
          BUILD_NUMBER="${{ inputs.build-number }}"
          echo "build-name-numbers=${BUILD_NAME}/${BUILD_NUMBER}" >> $GITHUB_OUTPUT

      - name: Get artifact version from JFrog build info
        id: get-artifact-version
        run: |
          BUILD_INFO='${{ steps.get-build-info.outputs.build-info }}'
          
          VERSION=$(echo "$BUILD_INFO" | jq -r '
            .buildInfo.modules[]
            | select(.id | test("-buildinfo-"))
            | .id
            | capture("-buildinfo-(?<ver>[^_]+)")
            | .ver
          ')
          
          if [[ -z "$VERSION" ]]; then
            echo "ERROR: Could not parse artifact version from JFrog build info!"
            exit 1
          fi
          
          echo "artifact-version=$VERSION" >> $GITHUB_OUTPUT

      - name: Debug show 'build-name-numbers' and 'artifact-version'
        run: |
          echo "build-name-number: ${{ steps.get-build-name-number.outputs.build-name-numbers }}"
          echo "artifact-version: ${{ steps.get-artifact-version.outputs.artifact-version }}"

      - name: Release debug
        run: |
          GIT_NOTES='${{ steps.get-release-notes.outputs.release-notes }}'
          RELEASE_VERSION='${{steps.get-artifact-version.outputs.artifact-version }}'
          echo "${RELEASE_VERSION}"
          echo "${GIT_NOTES}"

  publish-release-sonatype:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    needs: promote
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      # Needed since we are using actions which are part of the repository
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CLIENT_BOT_PAT }}

      # Pulling release from JFROG
      - uses: ./.github/actions/stage-release-artifacts
        with:
          oidc-provider: ${{ secrets.JFROG_OIDC_PROVIDER }}
          oidc-audience: ${{ secrets.JFROG_OIDC_AUDIENCE }}
          target-repository: ${{ inputs.target-repository }}
          build-name-number: ${{ needs.promote.outputs.build-name-number }}
          artifact-version: ${{ needs.promote.outputs.artifact-version }}

      # Publishing release to Maven Central
      - uses: ./.github/actions/publish-to-sonatype
        id: publish-to-sonatype
        with:
          build-name-number: ${{ needs.promote.outputs.build-name-number }}
          artifact-version: ${{ needs.promote.outputs.artifact-version }}
          publish-user: ${{ secrets.AEROSPIKE_SA_CICD_USERNAME }}
          publish-password: ${{ secrets.AEROSPIKE_SA_CICD_PASSWORD }}
          validation-max-number-checks: ${{ vars.VALIDATION_MAX_NUMBER_CHECKS }}
          sonatype-domain-name: ${{ vars.SONATYPE_DOMAIN_NAME }}
      
      # Publishing release information to JFrog for aggregation. This information is used later for final release step
      # (acknowledgement) to Maven Central
      - uses: ./.github/actions/publish-build-info-to-jfrog
        with:
          oidc-provider: ${{ secrets.JFROG_OIDC_PROVIDER }}
          oidc-audience: ${{ secrets.JFROG_OIDC_AUDIENCE }}
          build-path: ${{ needs.promote.outputs.build-name-number }}
          variables: '{"SONATYPE_STAGING_BUILD_ID":"${{ steps.publish-to-sonatype.outputs.maven-central-release-id }}"}'

  publish-release-github:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    needs: [promote, publish-release-sonatype]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.target-branch }}
          token: ${{ secrets.CLIENT_BOT_PAT }}

      - uses: ./.github/actions/stage-release-artifacts
        with:
          oidc-provider: ${{ secrets.JFROG_OIDC_PROVIDER }}
          oidc-audience: ${{ secrets.JFROG_OIDC_AUDIENCE }}
          target-repository: ${{ inputs.target-repository }}
          build-name-number: ${{ needs.promote.outputs.build-name-number }}
          artifact-version: ${{ needs.promote.outputs.artifact-version }}
          staging-folder: '["staging","github"]'

      # Publishing release to GitHub
      # Note: this action knows how to process json internally. It expects inputs to be in json format
      - uses: ./.github/actions/publish-to-github
        with:
          release-notes: ${{ needs.promote.outputs.release-notes }}
          github-token: ${{ secrets.CLIENT_BOT_PAT }}
          build-name-number: ${{ needs.promote.outputs.build-name-numbers }}
          artifact-version: ${{ needs.promote.outputs.artifact-version }}
