#  https://github.com/mheap/github-action-required-labels
name: Pull Request Required Labels
on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
jobs:
  label:
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    name: Verify Pull Request has labels
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Required-labels
        uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5.5.1
        with:
          mode: minimum
          count: 1
          labels: "breaking, breaks, feature, enhancement, fix, bugfix, bug, chore, cleanup, polish, dependencies, 
          documentation"
